### ISSUE TITLE
engine: insertNode

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3235]
(don't know how to reproduce for now)
```
[PANIC_RECOVERY] Stacktrace of 4096 bytes
goroutine 1879452 [running]:
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1.1(0xc457a89978, 0xc42fb3ea00, 0xc4206f60c0, 0x2885700, 0xc445695360)
	/go/src/github.com/ovh/cds/engine/api/router.go:111 +0x353
panic(0x21149c0, 0x286df20)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/ovh/cds/engine/api/workflow.insertNode(0x28b1600, 0xc457ce6840, 0x28b5740, 0xc4207360a0, 0xc42674b340, 0xc42674b600, 0xc46b214a20, 0xc426f2b000, 0x0, 0x0)
	/go/src/github.com/ovh/cds/engine/api/workflow/dao_node.go:139 +0xa77
github.com/ovh/cds/engine/api/workflow.Update(0x28b1600, 0xc457ce6840, 0x28b5740, 0xc4207360a0, 0xc42674b340, 0xc45770adc0, 0xc462f570e0, 0xc46b214a20, 0xc42674b340, 0x0)
	/go/src/github.com/ovh/cds/engine/api/workflow/dao.go:660 +0x34e
github.com/ovh/cds/engine/api.(*API).putWorkflowHandler.func1(0x2892dc0, 0xc44ecc1830, 0x2885700, 0xc445695360, 0xc42fb3ea00, 0x0, 0x0)
	/go/src/github.com/ovh/cds/engine/api/workflow.go:276 +0x62f
github.com/ovh/cds/engine/api.(*Router).Handle.func1(0x2885700, 0xc445695360, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/engine/api/router.go:231 +0x51a
net/http.HandlerFunc.ServeHTTP(0xc4207a0200, 0x2885700, 0xc445695360, 0xc42fb3ea00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1(0x2885700, 0xc445695360, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/engine/api/router.go:138 +0xab
net/http.HandlerFunc.ServeHTTP(0xc4207a0220, 0x2885700, 0xc445695360, 0xc42fb3ea00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/ovh/cds/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1(0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/handlers/compress.go:143 +0x458
net/http.HandlerFunc.ServeHTTP(0xc4207a0240, 0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(Handler).ServeHTTP-fm(0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/engine/api/router.go:91 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc4207a0260, 0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1.1(0x2892dc0, 0xc4593d7b00)
	/go/src/github.com/ovh/cds/engine/api/router.go:85 +0x45
runtime/pprof.Do(0x2892dc0, 0xc4593d7b00, 0xc451ce7b40, 0x1, 0x1, 0xc448b29bf8)
	/usr/local/go/src/runtime/pprof/runtime.go:35 +0xca
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1(0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/engine/api/router.go:84 +0x135
net/http.HandlerFunc.ServeHTTP(0xc42078de90, 0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/ovh/cds/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420228050, 0x2890bc0, 0xc438e121c0, 0xc42fb3ea00)
	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc4209904e0, 0x2890bc0, 0xc438e121c0, 0xc42fb3e800)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc442465d60, 0x2892d00, 0xc454e3b500)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

goroutine 1 [chan receive, 185 minutes]:
main.glob..func5(0x39ab2c0, 0xc4202af590, 0x1, 0x3)
	/go/src/github.com/ovh/cds/engine/main.go:531 +0x37fe
github.com/ovh/cds/vendor/github.com/spf13/cobra.(*Command).execute(0x39ab2c0, 0xc4202af530, 0x3, 0x3, 0x39ab2c0, 0xc4202af530)
	/go/src/github.com/ovh/cds/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/ovh/cds/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x39aa540, 0x0, 0x39ab080, 0x39aae40)
	/go/src/github.com/ovh/cds/vendor/github.com/spf13/cobra/command.go:831 +0x2e4
github.com/ovh/cds/vendor/github.com/spf13/cobra.(*Command).Execute(0x39aa540, 0xc4204a1f78, 0xc4200ba058)
	/go/src/github.com/ovh/cds/vendor/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/go/src/github.com/ovh/cds/engine/main.go:82 +0x2d

goroutine 6 [select]:
github.com/ovh/cds/vendor/go.opencensus.io/stats
```

**Comment by fsamin** [comment]
unable to reproduce
close
