### ISSUE TITLE
kafka-plugin rpc error

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3370]
sometimes:

```
Error running action: rpc error: code = Unavailable desc = transport is closing
End of step /plugin-kafka-publish-2 [Fail] with reason: Error running action: rpc error: code = Unavailable desc = transport is closing
```

**Comment by yesnault** [comment]
Don't know if it's a root cause or a consequence
```

retrieving interface for local IP
--
141 | no interface provided, looking for docker0
142 | analysing layer [sha256:56c81] 3/6
143 | analysing layer [sha256:2e793] 5/6
144 | analysing layer [sha256:4fe2a] 6/6
145 | Creating reportanic: runtime error: invalid memory address or nil pointer dereference
146 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x601b27]
147 |  
148 | goroutine 36 [running]:
149 | log.(*Logger).Output(0x0, 0x2, 0xc4202d7580, 0x36, 0x0, 0x0)
150 | /usr/local/go/src/log/log.go:153 +0x47
151 | log.(*Logger).Println(0x0, 0xc420667088, 0x1, 0x1)
152 | /usr/local/go/src/log/log.go:188 +0x6a
153 | github.com/ovh/cds/sdk/plugin.SendVulnerabilityReport(0xc40000a173, 0xc420253950, 0x0, 0x0, 0x0, 0xc8f853, 0x6, 0x0, 0xc420037d31)
154 | /go/src/github.com/ovh/cds/sdk/plugin/common.go:192 +0x633
155 | main.(*clairActionPlugin).Run(0xc42046a480, 0xd38100, 0xc42045be30, 0xc420468dc0, 0xc42046a480, 0xc42045bda0, 0xb8db60)
156 | /go/src/github.com/ovh/cds/contrib/grpcplugins/action/clair/main.go:97 +0xc95
157 | github.com/ovh/cds/sdk/grpcplugin/actionplugin._ActionPlugin_Run_Handler(0xbfff40, 0xc42046a480, 0xd38100, 0xc42045be30, 0xc420413ea0, 0x0, 0x0, 0x0, 0xc4203f097e, 0x0)
158 | Error running action: rpc error: code = Unavailable desc = transport is closing
159 | End of step /CDS_DockerPackage-2/plugin-clair-2 [Fail] with reason: Error running action: rpc error: code = Unavailable desc = transport is closing
160 | /go/src/github.com/ovh/cds/sdk/grpcplugin/actionplugin/actionplugin.pb.go:238 +0x241
161 | github.com/ovh/cds/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42037c380, 0xd3d9e0, 0xc420388a00, 0xc420394f00, 0xc42045b500, 0x1308d58, 0x0, 0x0, 0x0)
162 | /go/src/github.com/ovh/cds/vendor/google.golang.org/grpc/server.go:1011 +0x4fc
163 | github.com/ovh/cds/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42037c380, 0xd3d9e0, 0xc420388a00, 0xc420394f00, 0x0)
164 | /go/src/github.com/ovh/cds/vendor/google.golang.org/grpc/server.go:1249 +0x1318
165 | github.com/ovh/cds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4203f0780, 0xc42037c380, 0xd3d9e0, 0xc420388a00, 0xc420394f00)
166 | /go/src/github.com/ovh/cds/vendor/google.golang.org/grpc/server.go:680 +0x9f
167 | created by github.com/ovh/cds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
168 | /go/src/github.com/ovh/cds/vendor/google.golang.org/grpc/server.go:678 +0xa1


```

**Comment by yesnault** [comment]
fixed

**Comment by bnjjj** [comment]
another one `Error running action: rpc error: code = Unavailable desc = transport is closing`

**Comment by yesnault** [comment]
fixed in week 45
