### ISSUE TITLE
Missing default configs

### ISSUE THREAD

**Issue by drew9781** [ovh/cds#5716]
When following the binaries setup tutorial I ran into issued downloading the sql and ui files.

```
@cds:~$ /home/cds/cds/cds-engine download sql --config /home/cds/cds/conf.toml
Reading configuration file @ /home/cds/cds/conf.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x21c21ee]

goroutine 1 [running]:
main.glob..func8(0x461d960, 0xc000280380, 0x0, 0x2)
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/cmd_download.go:95 +0xde
github.com/spf13/cobra.(*Command).execute(0x461d960, 0xc000280360, 0x2, 0x2, 0x461d960, 0xc000280360)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.0-20171231101556-b95ab734e27d/command.go:750 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x461dde0, 0x0, 0x6, 0xc000098058)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.0-20171231101556-b95ab734e27d/command.go:831 +0x2c9
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.0-20171231101556-b95ab734e27d/command.go:784
main.main()
        /tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/main.go:26 +0x2d
```

This was due to these missing confs: 
```
DatabaseMigrate.Directory
UI.Staticdir
```
The doc doesn't mention them, I had to trace the code to find those

**Comment by yesnault** [comment]
I can't reproduce with fresh conf.toml (0.48.0).

```bash
> ls
cds-engine-darwin-amd64
> ./cds-engine-darwin-amd64 config new > conf.toml
> ls
cds-engine-darwin-amd64 conf.toml
> ./cds-engine-darwin-amd64 download sql --config conf.toml
Reading configuration file @ conf.toml
2021-02-26 17:53:50 [INFO] Directory sql has been created caller=main.downloadTarGzFromGithub source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/engine/cmd_download.go source_line=107
Downloading into sql...
Unarchive to sql
Download done.
> ls
cds-engine-darwin-amd64 conf.toml               sql
> ls sql
api cdn

```
btw, we need to check the key in conf before downloading

**Comment by drew9781** [comment]
Hm I generated a fresh conf.toml and all of the missing/empty keys are no longer empty :D 
I'm not sure what exactly caused my initial conf to have so many empty keys.

Thanks for the quick feedback!
